<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>model-notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="COPD-HAD-notes_files/libs/clipboard/clipboard.min.js"></script>
<script src="COPD-HAD-notes_files/libs/quarto-html/quarto.js"></script>
<script src="COPD-HAD-notes_files/libs/quarto-html/popper.min.js"></script>
<script src="COPD-HAD-notes_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="COPD-HAD-notes_files/libs/quarto-html/anchor.min.js"></script>
<link href="COPD-HAD-notes_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="COPD-HAD-notes_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="COPD-HAD-notes_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="COPD-HAD-notes_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="COPD-HAD-notes_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">model-notes</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="what-are-the-patient-characteristics-that-predict-worsening-depressionanxiety-in-copd-patients" class="level2">
<h2 class="anchored" data-anchor-id="what-are-the-patient-characteristics-that-predict-worsening-depressionanxiety-in-copd-patients">What are the patient characteristics that predict worsening depression/anxiety in COPD patients?&nbsp;</h2>
<ul>
<li><p>Dataset of 101 <a href="https://www.nhs.uk/conditions/chronic-obstructive-pulmonary-disease-copd/">Chronic obstructive pulmonary disease</a>&nbsp;COPD patients.&nbsp;</p></li>
<li><p>The HAD variable is the score from the Hospital Anxiety and Depression scale.</p></li>
<li><p>HADS score ranges from 0 to 21</p></li>
</ul>
</section>
<section id="choosing-predictor-variables" class="level2">
<h2 class="anchored" data-anchor-id="choosing-predictor-variables">Choosing predictor variables</h2>
<ul>
<li><p>Characteristics: Age, Gender, PackHistory, Smoking.</p></li>
<li><p>Disease: CAT, COPDSEVERITY.</p></li>
<li><p>Lung function: FEV1, FEV1PRED, FVCPRED, FVCPRED1.</p></li>
<li><p>Co-morbidities:</p></li>
</ul>
</section>
<section id="import-dataset" class="level2">
<h2 class="anchored" data-anchor-id="import-dataset">Import Dataset</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>COPD <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/COPD_student_dataset.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="missing-or-inaccurate-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-or-inaccurate-values">Missing or inaccurate values</h2>
<p>Inspecting variables with <code>summary()</code> reveals some unlikely looking ranges.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(COPD[[<span class="st">"HAD"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    6.00   10.00   11.18   15.00   56.20 </code></pre>
</div>
</div>
<p>The HAD score should range from 0 to 21, so there’s a least 1 incorrect value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(COPD[[<span class="st">"HAD"</span>]] <span class="sc">&gt;</span> <span class="dv">21</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(COPD[[<span class="st">"HAD"</span>]][COPD[[<span class="st">"HAD"</span>]] <span class="sc">&gt;</span> <span class="dv">21</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  22   23   26   29   30 56.2 
   3    2    2    1    2    1 </code></pre>
</div>
</div>
<p>In fact there are 11 values over 21. It looks as though the scale for this actually runs from 0 to 30. I’d like to take these questions back to the research team to confirm, but for the sake of this exercise I will just ignore 56.2 as the outlier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>COPD[[<span class="st">"HAD"</span>]][COPD[[<span class="st">"HAD"</span>]] <span class="sc">&gt;</span> <span class="dv">30</span>] <span class="ot">&lt;-</span> <span class="cn">NA_integer_</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similarly, CAT has a clearly separated max value. CAT is the COPD assessment test and according to the <a href="https://www.catestonline.org/content/dam/global/catestonline/documents/CAT_HCP%20User%20Guide.pdf" title="COPD Assessment Test FAQ">CAT user guide</a> is scored on a scale of 0-40.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(COPD[[<span class="st">"CAT"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   3.00   12.00   18.00   19.34   24.00  188.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(COPD[[<span class="st">"CAT"</span>]] <span class="sc">&gt;</span> <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Since there is just the one, I will exclude it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>COPD[[<span class="st">"CAT"</span>]][COPD[[<span class="st">"CAT"</span>]] <span class="sc">&gt;</span> <span class="dv">40</span>] <span class="ot">&lt;-</span> <span class="cn">NA_integer_</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="collinearity-of-predictor-candidates" class="level2">
<h2 class="anchored" data-anchor-id="collinearity-of-predictor-candidates">Collinearity of predictor candidates</h2>
<section id="correlation-in-continuous-variables" class="level3">
<h3 class="anchored" data-anchor-id="correlation-in-continuous-variables">Correlation in continuous variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>continuous_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PackHistory"</span>, <span class="st">"CAT"</span>, <span class="st">"FEV1"</span>, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"FEV1PRED"</span>, <span class="st">"FVC"</span>, <span class="st">"FVCPRED"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Pairwise scatterplots</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Correlation Matrix</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(COPD[, continuous_vars])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(COPD[, continuous_vars])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             PackHistory CAT       FEV1   FEV1PRED         FVC      FVCPRED
PackHistory  1.000000000  NA -0.1315051 -0.1313410 -0.09307289 -0.004489788
CAT                   NA   1         NA         NA          NA           NA
FEV1        -0.131505136  NA  1.0000000  0.7761105  0.82016501  0.515856013
FEV1PRED    -0.131340964  NA  0.7761105  1.0000000  0.52152997  0.625877533
FVC         -0.093072888  NA  0.8201650  0.5215300  1.00000000  0.622430376
FVCPRED     -0.004489788  NA  0.5158560  0.6258775  0.62243038  1.000000000</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="lung-function" class="level3">
<h3 class="anchored" data-anchor-id="lung-function">Lung Function</h3>
<p>There is strong correlation between the lung function measures FEV1, FEV1PRED, FVC and FVCPRED, so I will seek to include only one of the four, by exploring the individual relationships of each to HAD:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">FEV1</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">FEV1PRED</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">FVC</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href="">FVCPRED</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>FEV1_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> FEV1, COPD)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(FEV1_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ FEV1, data = COPD)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.869  -4.710  -1.278   3.932  18.128 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   14.622      1.858   7.871 4.78e-12 ***
FEV1          -2.435      1.072  -2.272   0.0253 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.188 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.05004,   Adjusted R-squared:  0.04035 
F-statistic: 5.162 on 1 and 98 DF,  p-value: 0.02527</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(HAD <span class="sc">~</span> FEV1, COPD)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(FEV1_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>FEV1PRED_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> FEV1PRED, COPD)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(FEV1PRED_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ FEV1PRED, data = COPD)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.819  -4.662  -1.654   4.731  19.298 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15.06450    2.02895   7.425 4.19e-11 ***
FEV1PRED    -0.07448    0.03260  -2.284   0.0245 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.186 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.05056,   Adjusted R-squared:  0.04087 
F-statistic: 5.218 on 1 and 98 DF,  p-value: 0.02451</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(HAD <span class="sc">~</span> FEV1PRED, COPD)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(FEV1PRED_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>FVC_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> FVC, COPD)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(FVC_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ FVC, data = COPD)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.161  -5.108  -1.560   4.502  18.147 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  14.4460     2.3162   6.237 1.13e-08 ***
FVC          -1.2586     0.7448  -1.690   0.0943 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.269 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.02831,   Adjusted R-squared:  0.01839 
F-statistic: 2.855 on 1 and 98 DF,  p-value: 0.09426</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(HAD <span class="sc">~</span> FVC, COPD)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(FVC_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>FVCPRED_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> FVCPRED, COPD)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(FVCPRED_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ FVCPRED, data = COPD)

Residuals:
    Min      1Q  Median      3Q     Max 
-12.010  -5.014  -1.193   4.286  19.529 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  18.5253     2.9301   6.322 7.66e-09 ***
FVCPRED      -0.0905     0.0330  -2.742  0.00725 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.107 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.07127,   Adjusted R-squared:  0.06179 
F-statistic:  7.52 on 1 and 98 DF,  p-value: 0.007254</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(HAD <span class="sc">~</span> FVCPRED, COPD)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(FVCPRED_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>They all have seem to be a slight negative predictor of HAD, but none of them explain the variation very well. The FVCPRED model has the highest adjusted R squared value at 0.06179.</p>
</section>
<section id="packhistory-and-smoking" class="level3">
<h3 class="anchored" data-anchor-id="packhistory-and-smoking">PackHistory and smoking</h3>
<p>PackHistory and smoking are both about a person’s smoking history. smoking is a categorical variable with value 1 for has smoked previously and 2 for currently smokes. PackHistory records a person’s pack years smoking, where pack years is defined as twenty cigarettes smoked every day for one year.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(COPD[[<span class="st">"smoking"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2 
16 85 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(COPD[[<span class="st">"smoking"</span>]], COPD[[<span class="st">"PackHistory"</span>]], <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.02234481</code></pre>
</div>
</div>
<p>They don’t appear to be highly correlated, but I still don’t think I want to include both. “smoking” is probably not that helpful given there are such a small number aren’t current smokers. I still want a bit more of a comparison though.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(COPD[[<span class="st">"smoking"</span>]], COPD[[<span class="st">"PackHistory"</span>]],</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Smoking status"</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Years of daily pack smoking"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Well, this has raised some concerns to me about PackHistory. If the unit is years the the number with 80+ looks suprising.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(COPD[[<span class="st">"PackHistory"</span>]] <span class="sc">&gt;</span> <span class="dv">80</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p>Ok, it’s only 6 which is not too bad, but since there is an AGE column I want to check how possible this is.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(COPD[[<span class="st">"PackHistory"</span>]] <span class="sc">&gt;</span> COPD[[<span class="st">"AGE"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14</code></pre>
</div>
</div>
<p>This feels a bit problematic. I’m not sure if the description I have about the measure is incorrect, or if it’s the data, but as this is &gt;10% of the dataset that looks impossible I think I’m going to have to ignore the this as a potential predictor. That’s also without adjusting for some assumption of a reasonable age people might start smoking.</p>
</section>
<section id="comborbidities" class="level3">
<h3 class="anchored" data-anchor-id="comborbidities">Comborbidities</h3>
<p>There are several binary variables relating to comorbidity</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>COPD<span class="sc">$</span>comorbid <span class="ot">&lt;-</span> COPD<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> COPD<span class="sc">$</span>muscular <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  COPD<span class="sc">$</span>hypertension <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> COPD<span class="sc">$</span>AtrialFib <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> COPD<span class="sc">$</span>IHD <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>COPD<span class="sc">$</span>comorbid <span class="ot">&lt;-</span> <span class="fu">factor</span>(COPD<span class="sc">$</span>comorbid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="disease-measure" class="level2">
<h2 class="anchored" data-anchor-id="disease-measure">Disease measure</h2>
<p>CAT and COPDSEVERITY are both measures of COPD disease status. CAT is a continuous score and COPDSEVERITY has three categories of severity. If both variables are suitable I will select the more detailed CAT.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">CAT</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">COPDSEVERITY</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(COPD[[<span class="st">"CAT"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   3.00   12.00   18.00   17.65   23.25   32.00       1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(HAD <span class="sc">~</span> CAT, COPD))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ CAT, data = COPD)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.5470  -4.1719  -0.9636   3.5531  15.6532 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.69666    1.51963   1.116    0.267    
CAT          0.51668    0.07896   6.544 2.84e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.161 on 97 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3063,    Adjusted R-squared:  0.2991 
F-statistic: 42.82 on 1 and 97 DF,  p-value: 2.839e-09</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(COPD[[<span class="st">"COPDSEVERITY"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       MILD    MODERATE      SEVERE VERY SEVERE 
         23          43          27           8 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(HAD <span class="sc">~</span> COPDSEVERITY, COPD))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ COPDSEVERITY, data = COPD)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.148  -5.116  -1.148   3.884  18.884 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                8.273      1.524   5.429 4.26e-07 ***
COPDSEVERITYMODERATE       1.844      1.874   0.984   0.3276    
COPDSEVERITYSEVERE         3.875      2.053   1.888   0.0621 .  
COPDSEVERITYVERY SEVERE    7.727      2.951   2.619   0.0103 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.147 on 96 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.07984,   Adjusted R-squared:  0.05108 
F-statistic: 2.777 on 3 and 96 DF,  p-value: 0.04542</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="trying-out-the-variables-as-predictors" class="level2">
<h2 class="anchored" data-anchor-id="trying-out-the-variables-as-predictors">Trying out the variables as predictors</h2>
<p>That leaves us with the following candidate predictor variables to explore</p>
<ul>
<li>AGE</li>
<li>gender</li>
<li>CAT</li>
<li>FVCPRED</li>
<li>comorbid</li>
</ul>
<p>It is known that age and gender impact depression. One might expect people with a worse disease condition i.e.&nbsp;higher CAT score to also have a worse HAD score. First I want to explore the relationship of each variable individually with the outcome HAD.</p>
<section id="characteristics" class="level3">
<h3 class="anchored" data-anchor-id="characteristics">Characteristics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>age_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> AGE, COPD)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(age_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ AGE, data = COPD)

Residuals:
    Min      1Q  Median      3Q     Max 
-12.554  -4.407  -1.103   3.659  20.081 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 25.50974    6.43149   3.966 0.000139 ***
AGE         -0.21069    0.09111  -2.312 0.022843 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.181 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.05174,   Adjusted R-squared:  0.04207 
F-statistic: 5.348 on 1 and 98 DF,  p-value: 0.02284</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(age_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 12.7466586 38.27282554
AGE         -0.3914899 -0.02988553</code></pre>
</div>
</div>
<p>The model suggests that for every 1 year of age, HAD score decreases by 0.21. So there does appear to be some relationship, but it doesn’t explain the variation in HAD very well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(HAD <span class="sc">~</span> AGE, COPD)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(age_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>gender_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> gender, COPD)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gender_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ gender, data = COPD)

Residuals:
    Min      1Q  Median      3Q     Max 
-12.000  -4.046  -1.023   4.954  18.000 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   12.000      1.236   9.706 5.26e-16 ***
gender        -1.954      1.533  -1.274    0.206    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.314 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.0163,    Adjusted R-squared:  0.006257 
F-statistic: 1.623 on 1 and 98 DF,  p-value: 0.2056</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(gender_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept)  9.546528 14.453472
gender      -4.997004  1.089311</code></pre>
</div>
</div>
<p>The p-value of 0.2 means we cannot rule out the null hypothesis of gender having no relationship to HAD score, and indeed the 95% confidence interval includes a gradient of 0. I will continue to explore this with gender alongside other variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(HAD <span class="sc">~</span> gender, COPD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see the HAD score distribution is fairly similar in men and women. I do want to check out age and gender alongside each other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>age_gender_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> AGE <span class="sc">+</span> gender, COPD)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(age_gender_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ AGE + gender, data = COPD)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.8001  -4.6953  -0.8481   4.1130  19.0821 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 25.51495    6.43430   3.965  0.00014 ***
AGE         -0.19726    0.09222  -2.139  0.03496 *  
gender      -1.45745    1.52404  -0.956  0.34129    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.184 on 97 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.0606,    Adjusted R-squared:  0.04123 
F-statistic: 3.129 on 2 and 97 DF,  p-value: 0.04822</code></pre>
</div>
</div>
<p>Do they have an impact through intersection?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>age_gender_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> AGE <span class="sc">*</span> gender, COPD)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(age_gender_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ AGE * gender, data = COPD)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.2680  -4.4037  -0.9083   3.9165  18.4149 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  9.59955   12.64044   0.759    0.449
AGE          0.03504    0.18365   0.191    0.849
gender      19.93655   14.73321   1.353    0.179
AGE:gender  -0.30942    0.21196  -1.460    0.148

Residual standard error: 7.143 on 96 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.081, Adjusted R-squared:  0.05228 
F-statistic: 2.821 on 3 and 96 DF,  p-value: 0.04299</code></pre>
</div>
</div>
<p>It doesn’t appear to be the case and seems like it might be more valuable to include AGE without gender.</p>
</section>
<section id="disease" class="level3">
<h3 class="anchored" data-anchor-id="disease">Disease</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>cat_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> CAT, COPD)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cat_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ CAT, data = COPD)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.5470  -4.1719  -0.9636   3.5531  15.6532 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.69666    1.51963   1.116    0.267    
CAT          0.51668    0.07896   6.544 2.84e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.161 on 97 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3063,    Adjusted R-squared:  0.2991 
F-statistic: 42.82 on 1 and 97 DF,  p-value: 2.839e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(cat_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) -1.3193823 4.7127094
CAT          0.3599729 0.6733953</code></pre>
</div>
</div>
<p>As a measure of disease I would expect CAT score to predict increased HAD score. Indeed, CAT looks like it’s going to be valuable to include, there is a clear positive relationship with HAD. That there is no relationship can be ruled out even at significance levels below 0.001.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(HAD <span class="sc">~</span> CAT, COPD)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(cat_lm, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="COPD-HAD-notes_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="comborbidities-1" class="level3">
<h3 class="anchored" data-anchor-id="comborbidities-1">Comborbidities</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>comorbid_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> comorbid, COPD)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(comorbid_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ comorbid, data = COPD)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.7593  -5.5811  -0.7593   4.6689  20.4783 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     9.522      1.075   8.861 3.58e-14 ***
comorbidTRUE    2.238      1.462   1.530    0.129    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.288 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.02333,   Adjusted R-squared:  0.01337 
F-statistic: 2.341 on 1 and 98 DF,  p-value: 0.1292</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(comorbid_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %    97.5 %
(Intercept)   7.3892986 11.654180
comorbidTRUE -0.6643639  5.139404</code></pre>
</div>
</div>
<p>No clear indication, but I want to check out if comorbodity interacts with disease/condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>cat_comorbid_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> CAT <span class="sc">+</span> comorbid <span class="sc">+</span> CAT <span class="sc">*</span> comorbid, COPD)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cat_comorbid_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ CAT + comorbid + CAT * comorbid, data = COPD)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.662  -3.998  -1.844   4.023  15.492 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        0.2758     2.0973   0.132    0.896    
CAT                0.5474     0.1119   4.890 4.09e-06 ***
comorbidTRUE       3.0817     3.0425   1.013    0.314    
CAT:comorbidTRUE  -0.0790     0.1584  -0.499    0.619    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.158 on 95 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3213,    Adjusted R-squared:  0.2999 
F-statistic: 14.99 on 3 and 95 DF,  p-value: 4.586e-08</code></pre>
</div>
</div>
<p>The relationship looks weaker, but I will note that the adjusted R squared is slightly higher than that of <span class="math inline">\(CAT\)</span> on it’s own, so it may better explain the variance, but p-values for both <span class="math inline">\(comorbid\)</span> and <span class="math inline">\(CAT * comorbid\)</span> are very high, making their null hypotheses significantly likely.</p>
</section>
</section>
<section id="selecting-multiple-variabels" class="level2">
<h2 class="anchored" data-anchor-id="selecting-multiple-variabels">Selecting multiple variabels</h2>
<p>more multiple combinations to make my final variable selection.I’m confident I want to include CAT, but want to try out some</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>multi_lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> CAT <span class="sc">+</span> FVCPRED <span class="sc">+</span> AGE <span class="sc">+</span> gender <span class="sc">+</span> comorbid, COPD)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(multi_lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ CAT + FVCPRED + AGE + gender + comorbid, data = COPD)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.0897  -4.2262  -0.7329   2.7345  16.7165 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  17.90909    6.42997   2.785  0.00648 ** 
CAT           0.45935    0.08132   5.648 1.75e-07 ***
FVCPRED      -0.03636    0.03000  -1.212  0.22849    
AGE          -0.17148    0.07770  -2.207  0.02977 *  
gender       -1.72259    1.29278  -1.332  0.18596    
comorbidTRUE  1.96907    1.22192   1.611  0.11047    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.962 on 93 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3772,    Adjusted R-squared:  0.3437 
F-statistic: 11.26 on 5 and 93 DF,  p-value: 1.658e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(multi_lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %      97.5 %
(Intercept)   5.14043738 30.67774911
CAT           0.29785634  0.62084225
FVCPRED      -0.09592529  0.02320335
AGE          -0.32577467 -0.01718824
gender       -4.28980514  0.84461913
comorbidTRUE -0.45740822  4.39555591</code></pre>
</div>
</div>
<p>This does bring the adjusted R-squared higher, but as with CAT and comorbid, FVCPRED, comorbid and gender have high p-values.</p>
<p>I’m not sure how best to interpret all of that together, but it does make me think it may be best to try just CAT and AGE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>cat_age_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(HAD <span class="sc">~</span> CAT <span class="sc">+</span> AGE, COPD)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cat_age_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = HAD ~ CAT + AGE, data = COPD)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.3435  -4.1107  -0.5489   3.4906  16.4015 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13.93262    5.71519   2.438   0.0166 *  
CAT          0.50484    0.07759   6.506 3.49e-09 ***
AGE         -0.17170    0.07743  -2.218   0.0289 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.04 on 96 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.3401,    Adjusted R-squared:  0.3263 
F-statistic: 24.73 on 2 and 96 DF,  p-value: 2.169e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(cat_age_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept)  2.5880619 25.27718425
CAT          0.3508179  0.65886693
AGE         -0.3253919 -0.01801275</code></pre>
</div>
</div>
<p>My feeling is this is the best model of the ones I’ve tried. Both CAT and AGE seem to have explanatory power over their respective null hypotheses. The adjusted R-squared value is higher than most of the other models I’ve tried at <span class="math inline">\(0.33\)</span>, but that’s still quite low if the potential max is 1, and so suggests not giving a great explanation of the variation.</p>
<p>I feel like I’m missing something, but I think this is my best first shot:</p>
<p><span class="math inline">\(HAD = 13.93 + 0.50 * CAT - 0.17 * AGE\)</span></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>